name: CI/CD Pipeline for Docker Images

on:
  push:
    branches:
      - main 
      - master
  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Pull Docker images
        run: |
          docker pull solomondocker10277/authwallet-app:latest
          docker pull solomondocker10277/placebetservice-app:latest
          docker pull solomondocker10277/adminbetting-app:latest
          docker pull solomondocker10277/mysql:latest
          
